apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.things.myorg.io
spec:
  group: things.myorg.io
  version: v1alpha1
  groupPriorityMinimum: 2000
  versionPriority: 10
  service:
    name: mytest-apiserver
    namespace: my-apiserver-system
    port: 443
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lSQU4yNnBER2NOelFpVlpJMExHRmp6MXN3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXhNUGJYa3RZWEJwYzJWeWRtVnlMV05oTUI0WERUSTFNRGd4TkRFMk1Ea3lPVm9YRFRJMQpNVEV4TWpFMk1Ea3lPVm93R2pFWU1CWUdBMVVFQXhNUGJYa3RZWEJwYzJWeWRtVnlMV05oTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMEhhWkVxSTNMK2lQcGZ1UEtQZGgwZCtKdFg1WEwzdDcKUEFrMUJwTWxJcjI3bXJFQ0RuTzVPeGkrS0VacFBUNlRDaHlqdXB2SkhDRG43NjBXZ1EvbXYrb09mQjh2b3pSSApZYk9BUjRtTEVtK3B4ZjZCaFBzZ3c3OHBiUnl1NER3R1Q1WlpiTGdqQW1PRFg2bDBiSlBRMVQwSnhkTlM2MXlBCjhCNlB6RWJYalJ2aWpyNjVBdmJZeVVaazk1c2Y0cU0xTEptRkZGSmw3cXVhYnJBTlJreXVaNjlXOGMxWC8zRE0KTFY3THd5NFJ0UVJiOGM2REFvQUZhbFZXSWVuQVhKM1MzcGJTYWdRUmlSYlY0NFZ0bHV2NUZmQW1HQWNhbGJhagpYaStoQi9NdGcwV0FZbVVMNDY4UWNnOTNWOVEycGFxWk9KdHQ0ZGZJSExEVXdmVHhSMFNGb1FJREFRQUJvMEl3ClFEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWZWTVgKd0Z6MVE2ZFIyWnR2Ui9heUVTM1FBSGN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUlhZmFQUGN0ZUdtbWdSeQpqbG45dWZPeDNScENYaXFuUWxMeUVYU3F6UnJrYUpPNjdvdm5Fc2h2a0ptMGNZUnlReEk2K1d4MkFjZkJ1MHIyCkwyMDNpOVdYN2NVeXpSSUFhTndtL2E4bm52RVBxMDdjK3o1YWRWTE5mWDJpRGZwQmI5MEx3eDFCTE1GaThOdVEKczd0ZkUyMm1ZbGhkTVRTa3I1M28xdFF1OE1DOWtVVGpTeTl0OWp3TExYblNHajgyaFZFM1RkWVVkL00vVVllZQpMNXBxWDgwV3BtOTVYRk41b0VKWXdhREVMMlpzc2p5bDdkeWhCRlFUQ0dxeXRVcTRaUXl2VmtGMEFxRHdhVlZlCnZZRHNZVVdVNzc2SWdBaTR4WXBuV01lQmNhNUxxTTlzK2lyV3A0MTFpd3ROYTh1QytHc1JLa2Y1Tkwvcy81bDkKdWJSaGZlcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= 
